const menu = [
  {
    id: 1,
    title: 'Paratha',
    category: 'breakfast',
    price: 30,
    img: './images/paratha.jpg',
    desc: `Golden-brown in color, flaky and layered, paratha is a type of Indian bread that is typically consumed for breakfast. The name comes from a combination of words parat and atta (flour).`,
  },
  {
    id: 2,
    title: 'Thali',
    category: 'lunch',
    price: 35,
    img: './images/Thali.jpg',
    desc: `Thali is a term that refers both to the Indian style of eating a meal and the round metal platter used for serving in parts of Asia and the Caribbean.`,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 50,
    img: './images/item-3.jpeg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'Puri',
    category: 'breakfast',
    price: 25,
    img: './images/Puri.jpg',
    desc: `Puri is an unleavened, fried Indian bread made with water, finer or coarser wheat flour, and occasionally cumin seeds. The dough is rolled into flat round shapes and fried in copious amounts of vegetable oil or ghee.... `,
  },
  {
    id: 5,
    title: 'Biryani',
    category: 'lunch',
    price: 150,
    img: './images/biryani.jpg',
    desc: `Biryani is a group of classic dishes dating back to the Mughal Empire. The main ingredients of biryani are rice (ideally basmati), spices, a base of meat, eggs, or vegetables. `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 50,
    img: './images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'Appam',
    category: 'breakfast',
    price: 30,
    img: './images/Appam.jpg',
    desc: `Appam is a popular Indian bowl-shaped pancake made from a batter of rice flour and coconut milk. Typically consumed for breakfast or dinner, appam is most popular in Tamil Nadu, Sri Lanka, and Kerala, `,
  },
  {
    id: 8,
    title: 'Roti',
    category: 'lunch',
    price: 35,
    img: './images/roti.jpg',
    desc: `Roti is a flat and unleavened bread made with wholemeal flour. It is traditionally cooked on an iron griddle called tava, an important vessel in the Indian cuisine. `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 15,
    img: './images/item-9.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
